### ISSUE TITLE
Error while running runsitecheck.py

### ISSUE THREAD

**Issue by jbauer123** [arkershaw/sitecheck#1]
Hi, I ran into an error on my first try of runsitecheck.py

Using default config...
Checking for updates...
Traceback (most recent call last):
  File "/usr/local/bin/runsitecheck.py", line 134, in <module>
    settings = urllib.request.urlopen(UPDATE_URL).read().decode('utf-8')
  File "/usr/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 461, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 571, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 499, in error
    return self._call_chain(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(_args)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/runsitecheck.py", line 138, in <module>
    print('Update check failed - please notify: {0}'.format(contact_email))
NameError: name 'contact_email' is not defined

**Comment by arkershaw** [comment]
Thanks for letting me know. Was this a release version or the latest source?
